name: CICD

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod 777 ./gradlew
          ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/weather_server .
      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather_server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}              # EC2 퍼블릭 IP 또는 DNS
          username: ${{ secrets.EC2_USER }}          # ec2-user, ubuntu 등
          key: ${{ secrets.EC2_SSH_KEY }}            # PEM 키 (그대로 값으로 저장)
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            set -e
            APP_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/weather_server:latest"
            APP_NAME="weather_server_container"                  # 컨테이너 이름 (고정)
            
            # Docker Hub 로그인 (필요 시)
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            
            # 최신 이미지 Pull
            docker pull $APP_IMAGE
            
            # 기존 컨테이너 중지 및 삭제 (있다면)
            if [ $(docker ps -q -f name=$APP_NAME) ]; then
              docker stop $APP_NAME
              docker rm $APP_NAME
            fi
            
            # 컨테이너 실행 (.env 파일 사용)
            docker run -d --restart unless-stopped \
              --name $APP_NAME \
              --env-file /home/ec2-user/.env \
              -p 8080:8080 \
              $APP_IMAGE
